const houses = [{
    ID: '1',
    Favorite: false,
    Address: '652 Avonwick Gate',
    City: 'Toronto',
    State: 'ON',
    ZipCode: 'M3A25',
    Beds: '4',
    Baths: '4',
    HouseSize: 7500,
    LotSize: '0.8',
    Price: 780000,
    Coordinates: '43.7507639, -79.3184378',
    Features: 'Dishwasher, Disposal, Separate laundry room, 3/4 bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Hardwood flooring in kitchen, Kitchen island, Solid surface countertops in kitchen, Entry foyer, Front living room, Ceiling fan in master bedroom, Master bedroom separate from other, Mirrored door closet in master bedroom, 2nd bedroom: 11x13, 3rd bedroom: 11x14, 4th Bedroom: 18x13, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Convection oven, Double built-in gas ovens, Gas cooktop, Gas stove, Marble/Stone floors',
    YearBuilt: '2008',
    Type: '0',
    Status: '1',
    Image: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/gallery/1.jpg',
    Agent: {
      Name: 'John Heart',
      Phone: '(213) 555-9392',
      Picture: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/employees/01.png',
    },
  },
  {
    ID: '2',
    Favorite: false,
    Address: '82649 Topeka St',
    City: 'Riverbank',
    State: 'CA',
    ZipCode: '95360',
    Beds: '5',
    Baths: '3',
    HouseSize: 12500,
    LotSize: '1.2',
    Price: 1750000,
    Coordinates: '37.7369999,-120.9430488',
    Features: 'Dishwasher, Disposal, Separate laundry room, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Breakfast Bar/Counter, Breakfast nook (eating area), Granite countertops in kitchen, Kitchen custom cabinets, Kitchen island, Pantry, Walk-in pantry, Entry foyer, Formal living room, Rear living room, Vaulted ceiling in living room, Balcony in master bedroom, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 13X20, 3rd bedroom: 13X17, 4th Bedroom: 13X18, 5th Bedroom: 14X16, Alarm system owned, Blinds, Built-in electric oven, Built-in microwave, Carpet, Ceiling fan(s), Gas cooktop, Intercom system, Marble/Stone floors, Water conditioner owned, Water filtering system, Window Coverings Throughout',
    YearBuilt: '2009',
    Type: '0',
    Status: '0',
    Image: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/gallery/2.jpg',
    Agent: {
      Name: 'Olivia Peyton',
      Phone: '(310) 555-2728',
      Picture: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/employees/09.png',
    },
  },
  {
    ID: '3',
    Favorite: false,
    Address: '328 S Kerema Ave',
    City: 'Milford',
    State: 'CT',
    ZipCode: '06465',
    Beds: '4',
    Baths: '2',
    HouseSize: 8356,
    LotSize: '0.04',
    Price: 350000,
    Coordinates: '41.1957999,-73.1022988',
    Features: 'Dishwasher, Disposal, Refrigerator, Separate laundry room, Washer/Dryer on 2nd floor, Full bath downstairs, Formal dining room, Downstairs family room, Separate family room, Wet bar in family room, Breakfast nook (eating area), Garden window in kitchen, Granite countertops in kitchen, Kitchen island, Marble/Stone flooring in kitchen, Pantry, Formal living room, Front living room, Master bedroom separate from other, Master bedroom upstairs, Sitting room in master bedroom, Walk-in closet in master bedroom, 2nd bedroom: 16x12, 3rd bedroom: 13x16, 4th Bedroom: 18x12, Alarm system owned, Built-in microwave, Carpet, Ceiling fan(s), Double built-in electric ovens, Gas cooktop, Marble/Stone floors',
    YearBuilt: '2010',
    Type: '0',
    Status: '0',
    Image: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/gallery/3.jpg',
    Agent: {
      Name: 'Robert Reagan',
      Phone: '(818) 555-2387',
      Picture: 'https://js.devexpress.com/jQuery/Demos/WidgetsGallery/JSDemos/images/employees/03.png',
    },
  },
  
  ].map((dataItem) => ({
    ...dataItem,
    formatCurrency: () => function (text, render) {
      return window.formatCurrency(parseInt(render(text), 10));
    },
    replaceFileExtension: () => function (text, render) {
      return render(text).replace('.jpg', 'b.jpg');
    },
  }));
  